version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    ports:
      - 3333:3000
    volumes:
     - type: bind
       source: ./app
       target: /yt
